name: Release HEAD

on:
  workflow_dispatch:

jobs:
  release-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Bump version
        run: |
          VERSION=$(jq -r '.version' package.json)
          SHA=$(git rev-parse --short=10 HEAD)
          npm version "${VERSION}-next-${SHA}"
      - name: Publish HEAD tagged as next
        run: npm publish --tag next
